ungrouped:
    hosts:
        dev:
            ansible_connection: local

task:
    hosts:
        node1:
            ansible_user: user
            ansible_host: 188.166.67.18

        node2:
            ansible_user: user
            ansible_host: 188.166.69.50

        node3:
            ansible_user: user
            ansible_host: 161.35.144.15
