ungrouped:
    hosts:
        dev:
            ansible_connection: local

task:
    hosts:
        node1:
            ansible_user: user
            ansible_host: 64.225.78.68

        node2:
            ansible_user: user
            ansible_host: 174.138.6.225

        node3:
            ansible_user: user
            ansible_host: 161.35.81.18
