apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoscale-app
  name: autoscale-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: autoscale-app
  type: LoadBalancer

