ungrouped:
    hosts:
        dev:
            ansible_connection: local

task:
    hosts:
        node1:
            ansible_user: user
            ansible_host: $node1_ip

        node2:
            ansible_user: user
            ansible_host: $node2_ip

        node3:
            ansible_user: user
            ansible_host: $node3_ip
